### ISSUE TITLE
Non-Object Value Error

### ISSUE THREAD

**Issue by mrippey** [twilio-labs/socless#79]
OS: Monterey, Version 12.3.1
npm version: 8.6.0
node version:  v16 & v18.0.0
serverless version: Framework Core: 3.15.2 (local) 3.15.2 (global)
Plugin: 6.2.2
SDK: 4.3.2
----------------------------------------------------------------------

Upon running npm run dev (even with the --force option), I receive the following : 

> file:///Users/m_a_t/socless/node_modules/lambda-packager/build/lib/packaging.js:126
>                         throw new Error(errors.error);
                              ^

> Error: Directory of code to package does not exist: layers does not exist
>    at file:///Users/m_a_t/socless/node_modules/lambda-packager/build/lib/packaging.js:126:31
>    at step (file:///Users/m_a_t/socless/node_modules/lambda-packager/build/lib/packaging.js:43:23)
>    at Object.next (file:///Users/m_a_t/socless/node_modules/lambda-packager/build/lib/packaging.js:24:53)
>    at file:///Users/m_a_t/socless/node_modules/lambda-packager/build/lib/packaging.js:18:71
>    at new Promise (<anonymous>)
>    at __awaiter (file:///Users/m_a_t/socless/node_modules/lambda-packager/build/lib/packaging.js:14:12)
>    at makePackages (file:///Users/m_a_t/socless/node_modules/lambda-packager/build/lib/packaging.js:118:12)
>    at Object.handler (file:///Users/m_a_t/socless/node_modules/lambda-packager/build/src/main.js:93:9)
>    at Object.run (/Users/m_a_t/socless/node_modules/cmd-ts/dist/cjs/command.js:150:41)
>    at async runSafely (/Users/m_a_t/socless/node_modules/cmd-ts/dist/cjs/runner.js:38:24)

I am by no means an expert in JavaScript, but I do not understand the issue with the "throw new Error" line, and the files the second error prints, are indeed within the Socless folder.

The program continues until the next error as seen below:

> socless@1.0.0 dev
> serverless deploy $npm_package_config_dev --aws-profile $npm_package_config_aws_profile --verbose

> StepFunctions logging not enabled. To ship playbook logs, set custom.sls_apb.logging = true in serverless.yml
> Rendering State Machine for ./playbooks/socless_core_integration_test/playbook.json...

> Error:
> Non-object value specified in resources array: ${{file(resources/dynamodb.yml)}}

The dynamodb.yml file was untouched, and googling for the above error has not been fruitful thus far. 

Any suggestions would be greatly appreciated.

**Comment by noxasaxon** [comment]
Hi @mrippey, thanks for the detailed bug report! 

Can you try again from this branch and let me know what it says? https://github.com/twilio-labs/socless/tree/remove-layers-from-pjson

**Comment by noxasaxon** [comment]
Ahh actually this is because you're using serverless 3.x.x, which we do not support yet

**Comment by mrippey** [comment]
Hey @noxasaxon, apologies for just now seeing this, I didn't receive a notification. I will try with a different version of serverless and see what happens.
